### ISSUE TITLE
Have you looked into this project, it's creating something similar to your idea. https://github.com/pancake-llc/foundation

### ISSUE THREAD

**Issue by IAFahim** [VirtueSky/sunflower#2]

**Comment by VirtueSky** [comment]
That's right, I took reference from that project and learned from it. The author of that project is my mentor.

**Comment by VirtueSky** [comment]
I am in the process of learning and upgrading myself. Foundation is a great product and I use it too, have you used it to build any game products?
And I created this repo to note down what I have learned.

**Comment by IAFahim** [comment]
> I am in the process of learning and upgrading myself. Foundation is a great product and I use it too, have you used it to build any game products?

I am trying create a fork to use in URP. It's still bit complex for me grasp all part of the packages, now currently learning. He is quite smart, you are also quite bright. Thank you for replying.
